## Class: 26SS INFO 2648 WW

## Name: Louis Colbert III

Program 

Write a program using the attached datasets above by doing the following:

1. Provide a count of all the missing values for columns "LotFrontage" and "Alley".
2. Use interpolate to fill missing values for rows 7 - 17 and columns 0 - 8. 
3. Display a second subset for data that fills missing values with "none" for rows 7 - 17 and columns 0 - 8.

In [101]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [102]:
df = pd.read_csv("data/train.csv")

In [103]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [105]:
# gathered the missing lotfrontage data count
missing_frontage = df['LotFrontage'].isna().sum()

In [106]:
missing_frontage

np.int64(259)

In [107]:
# got the missing alley data count
missing_alley = df['Alley'].isna().sum()

In [108]:
missing_alley

np.int64(1369)

In [109]:
#made a copy of the data to be used to not ruin the base data.
df_interpolated = df.copy()

In [110]:
# getting the subset of the data
subset_of_interpolate = df_interpolated.iloc[7:18, 0:9]

In [111]:
#checking the data
subset_of_interpolate

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl

In [112]:
subset_of_interpolate.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 7 to 17
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           11 non-null     int64
 1   MSSubClass   11 non-null     int64
 2   MSZoning     11 non-null     str
 3   LotFrontage  7 non-null      float64
 4   LotArea      11 non-null     int64
 5   Street       11 non-null     str
 6   Alley        0 non-null      str
 7   LotShape     11 non-null     str
 8   LandContour  11 non-null     str
dtypes: float64(1), int64(3), str(5)
memory usage: 924.0 bytes

In [113]:
#converting the data to a number to run interpolate
subset_of_interpolate['Alley'] = pd.to_numeric(subset_of_interpolate['Alley'])

In [114]:
subset_of_interpolate.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 7 to 17
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           11 non-null     int64
 1   MSSubClass   11 non-null     int64
 2   MSZoning     11 non-null     str
 3   LotFrontage  7 non-null      float64
 4   LotArea      11 non-null     int64
 5   Street       11 non-null     str
 6   Alley        0 non-null      float64
 7   LotShape     11 non-null     str
 8   LandContour  11 non-null     str
dtypes: float64(2), int64(3), str(4)
memory usage: 924.0 bytes

In [115]:
subset_of_interpolate['LotFrontage'] =  subset_of_interpolate['LotFrontage'].interpolate(method="linear",limit_direction="both")

In [116]:
subset_of_interpolate.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 7 to 17
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           11 non-null     int64
 1   MSSubClass   11 non-null     int64
 2   MSZoning     11 non-null     str
 3   LotFrontage  11 non-null     float64
 4   LotArea      11 non-null     int64
 5   Street       11 non-null     str
 6   Alley        0 non-null      float64
 7   LotShape     11 non-null     str
 8   LandContour  11 non-null     str
dtypes: float64(2), int64(3), str(4)
memory usage: 924.0 bytes

In [117]:
subset_of_interpolate['Alley'] = subset_of_interpolate['Alley'].interpolate(method= "linear", limit_direction="both")

### 2. Use interpolate to fill missing values for rows 7 - 17 and columns 0 - 8.

In [118]:
subset_of_interpolate

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour
7,8,60,RL,51.0,10382,Pave,NaN,IR1,Lvl
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl
12,13,20,RL,88.0,12968,Pave,NaN,IR2,Lvl
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl
14,15,20,RL,71.0,10920,Pave,NaN,IR1,Lvl
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl
16,17,20,RL,61.5,11241,Pave,NaN,IR1,Lvl
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl

### 3. Display a second subset for data that fills missing values with "none" for rows 7 - 17 and columns 0 - 8.

In [119]:
# Fill missing values with the string "none"
subset_of_interpolate = subset_none.fillna("none")

In [120]:
subset_of_interpolate

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour
7,8,60,RL,none,10382,Pave,none,IR1,Lvl
8,9,50,RM,51.0,6120,Pave,none,Reg,Lvl
9,10,190,RL,50.0,7420,Pave,none,Reg,Lvl
10,11,20,RL,70.0,11200,Pave,none,Reg,Lvl
11,12,60,RL,85.0,11924,Pave,none,IR1,Lvl
12,13,20,RL,none,12968,Pave,none,IR2,Lvl
13,14,20,RL,91.0,10652,Pave,none,IR1,Lvl
14,15,20,RL,none,10920,Pave,none,IR1,Lvl
15,16,45,RM,51.0,6120,Pave,none,Reg,Lvl
16,17,20,RL,none,11241,Pave,none,IR1,Lvl
17,18,90,RL,72.0,10791,Pave,none,Reg,Lvl