## Name: Louis Colbert III
## Class: 2648 WW

Assignment: Data Aggregation, Filtering, and Transformation with Pandas GroupBy

Objectives: 

Use the groupby method to aggregate data.
Use the groupby method to transform data.
Use the groupby method to filter data.
Instructions:

1. Dataset Selection:

Select a dataset of your choice (e.g., CSV, Excel, or online resource). Ensure that the dataset contains categorical and numerical columns suitable for aggregation, filtering, and transformation operations. *You can use the same dataset you are using for your final project if you wish.*

2. Loading the Dataset:

Load the dataset into a Pandas DataFrame.

3. Exploratory Data Analysis:

Perform initial exploratory data analysis to understand the structure of the dataset, check for missing values, and get a general idea of the data distribution.

4. Grouping and Aggregation:

Using the groupby function along with aggregation methods, perform the following tasks:

Calculate a summary statistic (e.g., mean, sum, count) for numerical columns within each group.
5. Filtering Data:

Apply filtering operations on the grouped data:

Filter out groups that meet specific conditions (e.g., exclude groups with a count below a certain threshold).
Make sure to note what you are excluding
6. Transforming Data:

Perform a data transformation within groups:

Create a new column containing a transformed value of a numerical column for a specific group
8. Conclusion:

Summarize your findings from the aggregation, filtering, and transformation operations. What did you learn about your dataset? What challenges did you encounter?

Submission Guidelines:

Submit your assignment in the form of a Jupyter Notebook or a script containing Python code, comments explaining the steps taken, and conclusions drawn from the dataset exploration using the GitHub Assignment Link below this assignment.

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import scipy.stats as sp

In [2]:
%matplotlib inline

In [3]:
import seaborn as sns
sns.set_theme()

In [6]:
df = pd.read_csv(r"C:\Users\lcolb\OneDrive\Documents\School\MCC\current\2026\Summer\Programming for Data Analytics\Datasets\datasets\data\acs_ny.csv")

In [7]:
df

,Acres,FamilyIncome,FamilyType,NumBedrooms,NumChildren,NumPeople,NumRooms,NumUnits,NumVehicles,NumWorkers,OwnRent,YearBuilt,HouseCosts,ElectricBill,FoodStamp,HeatingFuel,Insurance,Language
0,1-10,150,Married,4,1,3,9,Single detached,1,0,Mortgage,1950-1959,1800,90,No,Gas,2500,English
1,1-10,180,Female Head,3,2,4,6,Single detached,2,0,Rented,Before 1939,850,90,No,Oil,0,English
2,1-10,280,Female Head,4,0,2,8,Single detached,3,1,Mortgage,2000-2004,2600,260,No,Oil,6600,Other European
3,1-10,330,Female Head,2,1,2,4,Single detached,1,0,Rented,1950-1959,1800,140,No,Oil,0,English
4,1-10,330,Male Head,3,1,2,5,Single attached,1,0,Mortgage,Before 1939,860,150,No,Gas,660,Spanish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22740,10+,565000,Married,5,3,5,10,Single detached,2,2,Mortgage,1990-1999,1700,370,No,Gas,1000,English
22741,10+,599000,Married,4,0,2,6,Single detached,2,2,Mortgage,Before 1939,1300,100,No,Gas,3500,English
22742,10+,611700,Married,4,1,5,9,Single detached,5,3,Mortgage,Before 1939,410,100,No,Oil,1300,Spanish
22743,10+,621430,Married,3,2,4,11,Single detached,2,3,Mortgage,1970-1979,1600,80,No,Gas,800,Spanish
22744,10+,751200,Married,4,2,4,10,Single detached,2,2,Mortgage,1940-1949,6500,400,No,Oil,2000,English

In [8]:
df.head(4)

,Acres,FamilyIncome,FamilyType,NumBedrooms,NumChildren,NumPeople,NumRooms,NumUnits,NumVehicles,NumWorkers,OwnRent,YearBuilt,HouseCosts,ElectricBill,FoodStamp,HeatingFuel,Insurance,Language
0,1-10,150,Married,4,1,3,9,Single detached,1,0,Mortgage,1950-1959,1800,90,No,Gas,2500,English
1,1-10,180,Female Head,3,2,4,6,Single detached,2,0,Rented,Before 1939,850,90,No,Oil,0,English
2,1-10,280,Female Head,4,0,2,8,Single detached,3,1,Mortgage,2000-2004,2600,260,No,Oil,6600,Other European
3,1-10,330,Female Head,2,1,2,4,Single detached,1,0,Rented,1950-1959,1800,140,No,Oil,0,English

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22745 entries, 0 to 22744
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Acres         22745 non-null  str
 1   FamilyIncome  22745 non-null  int64
 2   FamilyType    22745 non-null  str
 3   NumBedrooms   22745 non-null  int64
 4   NumChildren   22745 non-null  int64
 5   NumPeople     22745 non-null  int64
 6   NumRooms      22745 non-null  int64
 7   NumUnits      22745 non-null  str
 8   NumVehicles   22745 non-null  int64
 9   NumWorkers    22745 non-null  int64
 10  OwnRent       22745 non-null  str
 11  YearBuilt     22745 non-null  str
 12  HouseCosts    22745 non-null  int64
 13  ElectricBill  22745 non-null  int64
 14  FoodStamp     22745 non-null  str
 15  HeatingFuel   22722 non-null  str
 16  Insurance     22745 non-null  int64
 17  Language      22745 non-null  str
dtypes: int64(10), str(8)
memory usage: 3.1 MB

In [13]:
df.isnull().value_counts()

Acres  FamilyIncome  FamilyType  NumBedrooms  NumChildren  NumPeople  NumRooms  NumUnits  NumVehicles  NumWorkers  OwnRent  YearBuilt  HouseCosts  ElectricBill  FoodStamp  HeatingFuel  Insurance  Language
False  False         False       False        False        False      False     False     False        False       False    False      False       False         False      False        False      False       22722
                                                                                                                                                                            True         False      False          23
Name: count, dtype: int64

In [14]:
df.describe()

,FamilyIncome,NumBedrooms,NumChildren,NumPeople,NumRooms,NumVehicles,NumWorkers,HouseCosts,ElectricBill,Insurance
count,2.274500e+04,22745.000000,22745.000000,22745.000000,22745.000000,22745.000000,22745.000000,22745.000000,22745.000000,22745.000000
mean,1.102814e+05,3.385315,0.901165,3.390459,7.174764,2.112640,1.744647,1480.471840,175.022950,960.924071
std,1.004539e+05,1.092477,1.159535,1.407659,2.345623,0.969129,0.822566,1150.248288,106.705696,995.461359
min,5.000000e+01,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000
25%,5.254000e+04,3.000000,0.000000,2.000000,6.000000,2.000000,1.000000,650.000000,100.000000,400.000000
50%,8.700000e+04,3.000000,0.000000,3.000000,7.000000,2.000000,2.000000,1200.000000,150.000000,720.000000
75%,1.338000e+05,4.000000,2.000000,4.000000,8.000000,3.000000,2.000000,2000.000000,220.000000,1200.000000
max,1.605000e+06,8.000000,12.000000,18.000000,21.000000,6.000000,3.000000,7090.000000,580.000000,6600.000000

In [17]:
df.shape

(22745, 18)

In [23]:
df.columns

Index(['Acres', 'FamilyIncome', 'FamilyType', 'NumBedrooms', 'NumChildren',
       'NumPeople', 'NumRooms', 'NumUnits', 'NumVehicles', 'NumWorkers',
       'OwnRent', 'YearBuilt', 'HouseCosts', 'ElectricBill', 'FoodStamp',
       'HeatingFuel', 'Insurance', 'Language'],
      dtype='str')

In [24]:
df.columns = df.columns.str.strip()

In [26]:
df2 = df[['FamilyIncome', 'NumBedrooms', 'NumChildren', 'NumPeople', 'NumRooms', 'NumVehicles', 'NumWorkers', 'HouseCosts','ElectricBill', 'Insurance']]

In [28]:
df2.head()

,FamilyIncome,NumBedrooms,NumChildren,NumPeople,NumRooms,NumVehicles,NumWorkers,HouseCosts,ElectricBill,Insurance
0,150,4,1,3,9,1,0,1800,90,2500
1,180,3,2,4,6,2,0,850,90,0
2,280,4,0,2,8,3,1,2600,260,6600
3,330,2,1,2,4,1,0,1800,140,0
4,330,3,1,2,5,1,0,860,150,660

In [29]:
df2.groupby('NumChildren')['FamilyIncome'].agg(['mean'])

                      mean
NumChildren
0            106584.894997
1            108440.171665
2            119009.694826
3            122769.560856
4            103504.732824
5             99076.380952
6            100900.648649
7             44404.666667
8             52500.000000
9             35200.000000
10            50915.000000
12            81600.000000

In [40]:
df3 = df.groupby('Language')[['FamilyIncome', 'NumBedrooms', 'NumChildren', 'NumPeople', 'NumRooms', 'NumVehicles', 'NumWorkers', 'HouseCosts','ElectricBill', 'Insurance']].agg(['mean', 'count', 'sum']).round()

In [41]:
df3.head()

               FamilyIncome                    NumBedrooms                \
                       mean  count         sum        mean  count    sum
Language
Asian Pacific      126038.0    804   101334733         3.0    804   2731
English            108620.0  17845  1938330345         3.0  17845  59859
Other              134087.0    284    38080791         4.0    284   1051
Other European     125835.0   2026   254940952         4.0   2026   7251
Spanish             98355.0   1786   175662669         3.0   1786   6107

               NumChildren               NumPeople  ... NumWorkers HouseCosts  \
                      mean  count    sum      mean  ...        sum       mean
Language                                            ...
Asian Pacific          1.0    804    720       4.0  ...       1518     2181.0
English                1.0  17845  15223       3.0  ...      30692     1359.0
Other                  2.0    284    454       4.0  ...        506     2109.0
Other European         1.0   2026   2137       4.0  ...       3719     1952.0
Spanish                1.0   1786   1963       4.0  ...       3247     1739.0

                                ElectricBill                 Insurance         \
                count       sum         mean  count      sum      mean  count
Language
Asian Pacific     804   1753664        167.0    804   134587    1047.0    804
English         17845  24259612        170.0  17845  3040943     926.0  17845
Other             284    598970        206.0    284    58631    1320.0    284
Other European   2026   3954488        197.0   2026   399614    1222.0   2026
Spanish          1786   3106598        194.0   1786   347122     913.0   1786


                     sum
Language
Asian Pacific     841974
English         16531542
Other             374810
Other European   2476434
Spanish          1631458

[5 rows x 30 columns]

In [54]:
filtered = df3[df3[('FamilyIncome','count')] >= 500]
df3

               FamilyIncome                    NumBedrooms                \
                       mean  count         sum        mean  count    sum
Language
Asian Pacific      126038.0    804   101334733         3.0    804   2731
English            108620.0  17845  1938330345         3.0  17845  59859
Other              134087.0    284    38080791         4.0    284   1051
Other European     125835.0   2026   254940952         4.0   2026   7251
Spanish             98355.0   1786   175662669         3.0   1786   6107

               NumChildren               NumPeople  ... NumWorkers HouseCosts  \
                      mean  count    sum      mean  ...        sum       mean
Language                                            ...
Asian Pacific          1.0    804    720       4.0  ...       1518     2181.0
English                1.0  17845  15223       3.0  ...      30692     1359.0
Other                  2.0    284    454       4.0  ...        506     2109.0
Other European         1.0   2026   2137       4.0  ...       3719     1952.0
Spanish                1.0   1786   1963       4.0  ...       3247     1739.0

                                ElectricBill                 Insurance         \
                count       sum         mean  count      sum      mean  count
Language
Asian Pacific     804   1753664        167.0    804   134587    1047.0    804
English         17845  24259612        170.0  17845  3040943     926.0  17845
Other             284    598970        206.0    284    58631    1320.0    284
Other European   2026   3954488        197.0   2026   399614    1222.0   2026
Spanish          1786   3106598        194.0   1786   347122     913.0   1786


                     sum
Language
Asian Pacific     841974
English         16531542
Other             374810
Other European   2476434
Spanish          1631458

[5 rows x 30 columns]

In [55]:
df3[('FamilyIncome', 'income_share')] = (
    df3[('FamilyIncome', 'sum')] / df3[('FamilyIncome', 'sum')].sum()
)
df3.head()

               FamilyIncome                    NumBedrooms                \
                       mean  count         sum        mean  count    sum
Language
Asian Pacific      126038.0    804   101334733         3.0    804   2731
English            108620.0  17845  1938330345         3.0  17845  59859
Other              134087.0    284    38080791         4.0    284   1051
Other European     125835.0   2026   254940952         4.0   2026   7251
Spanish             98355.0   1786   175662669         3.0   1786   6107

               NumChildren               NumPeople  ... HouseCosts         \
                      mean  count    sum      mean  ...       mean  count
Language                                            ...
Asian Pacific          1.0    804    720       4.0  ...     2181.0    804
English                1.0  17845  15223       3.0  ...     1359.0  17845
Other                  2.0    284    454       4.0  ...     2109.0    284
Other European         1.0   2026   2137       4.0  ...     1952.0   2026
Spanish                1.0   1786   1963       4.0  ...     1739.0   1786

                         ElectricBill                 Insurance         \
                     sum         mean  count      sum      mean  count
Language
Asian Pacific    1753664        167.0    804   134587    1047.0    804
English         24259612        170.0  17845  3040943     926.0  17845
Other             598970        206.0    284    58631    1320.0    284
Other European   3954488        197.0   2026   399614    1222.0   2026
Spanish          3106598        194.0   1786   347122     913.0   1786

                         FamilyIncome
                     sum income_share
Language
Asian Pacific     841974     0.040399
English         16531542     0.772751
Other             374810     0.015182
Other European   2476434     0.101637
Spanish          1631458     0.070031

[5 rows x 31 columns]

Through the grouping aggregations and filtering some insigths come to to fruition using the ACS NY daataset.  
The income varies significantly by language when aggregating the data. , secondly the household structure differes across the various groyps.
Filtering did reveal meaninful patters where we could see that excluding groups fewer than 500 observations allowed it to be less noisy and stabilized the data.