# Name: Louis Colbert III

## Class: INFO 2648 WW

Program 

Write a program using the attached datasets above by doing the following:

1. Display a sample of the attached data's first 5 line.
2. Melt/Pivot columns "Selling Price", "Original Price", "Operating System" and "Rating", then display the top 5 line and the bottom 5 lines. 
3. Display a filtered sample of the melted data showing only the TOSHIBA brand.

In [42]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [43]:
df = pd.read_csv("TV_Final.csv")

In [44]:
df.head()

,Brand,Resolution,Size,Selling Price,Original Price,Operating System,Rating
0,TOSHIBA,Ultra HD LED,55,37999,54990,VIDAA,4.3
1,TCL,QLED Ultra HD,55,52999,129990,Android,4.4
2,realme,HD LED,32,13999,17999,Android,4.3
3,Mi,HD LED,32,14999,19999,Android,4.4
4,realme,HD LED,32,12999,21999,Android,4.3

In [45]:
MELT_COLS = ["Selling Price", "Original Price", "Operating System", "Rating"]

In [46]:
def get_id_vars(df, melt_cols):
    """
    Return the columns in the df that are NOT melts
    these are used as the Identifier columns
    """

    return [col for col in df.columns if col not in melt_cols]

In [47]:
def melt_price_os_rating(df, melt_cols=None):

    if melt_cols is None:
        melt_cols = MELT_COLS

    id_vars =  get_id_vars(df, melt_cols)

    melted_df = pd.melt(
    df, 
    id_vars= id_vars,
    value_vars=melt_cols,
    var_name="Attribute",
    value_name="Value"
    )
    return melted_df

In [48]:
df_melted = melt_price_os_rating(df)

In [49]:
df_melted.head()

     Brand     Resolution  Size      Attribute  Value
0  TOSHIBA   Ultra HD LED    55  Selling Price  37999
1     TCL   QLED Ultra HD    55  Selling Price  52999
2  realme          HD LED    32  Selling Price  13999
3      Mi          HD LED    32  Selling Price  14999
4  realme          HD LED    32  Selling Price  12999

In [50]:
df_melted.tail()

      Brand    Resolution  Size Attribute Value
3643  SONY    Full HD LED    43    Rating   4.4
3644  SONY    Full HD LED    40    Rating   4.6
3645  SONY   Ultra HD LED    65    Rating   4.3
3646  SONY         HD LED    32    Rating   4.4
3647  SONY    Full HD LED    43    Rating   4.6

In [51]:
df_melted[df_melted['Brand'] == 'TOSHIBA']

        Brand    Resolution  Size         Attribute   Value
0     TOSHIBA  Ultra HD LED    55     Selling Price   37999
19    TOSHIBA  Ultra HD LED    43     Selling Price   27999
26    TOSHIBA        HD LED    32     Selling Price   12499
132   TOSHIBA   Full HD LED    43     Selling Price   22499
232   TOSHIBA  Ultra HD LED    50     Selling Price   33999
234   TOSHIBA        HD LED    32     Selling Price   17499
487   TOSHIBA  Ultra HD LED    65     Selling Price   63999
529   TOSHIBA  Ultra HD LED    55     Selling Price   40599
618   TOSHIBA  Ultra HD LED    43     Selling Price   28999
876   TOSHIBA   Full HD LED    43     Selling Price   24999
877   TOSHIBA  Ultra HD LED    65     Selling Price   66999
878   TOSHIBA   Full HD LED    49     Selling Price   29999
879   TOSHIBA  Ultra HD LED    65     Selling Price   96999
912   TOSHIBA  Ultra HD LED    55    Original Price   54990
931   TOSHIBA  Ultra HD LED    43    Original Price   39990
938   TOSHIBA        HD LED    32    Original Price   14990
1044  TOSHIBA   Full HD LED    43    Original Price   26990
1144  TOSHIBA  Ultra HD LED    50    Original Price   46990
1146  TOSHIBA        HD LED    32    Original Price   18990
1399  TOSHIBA  Ultra HD LED    65    Original Price  119999
1441  TOSHIBA  Ultra HD LED    55    Original Price   50999
1530  TOSHIBA  Ultra HD LED    43    Original Price   38999
1788  TOSHIBA   Full HD LED    43    Original Price   31990
1789  TOSHIBA  Ultra HD LED    65    Original Price   84990
1790  TOSHIBA   Full HD LED    49    Original Price   51999
1791  TOSHIBA  Ultra HD LED    65    Original Price  133990
1824  TOSHIBA  Ultra HD LED    55  Operating System   VIDAA
1843  TOSHIBA  Ultra HD LED    43  Operating System   VIDAA
1850  TOSHIBA        HD LED    32  Operating System   VIDAA
1956  TOSHIBA   Full HD LED    43  Operating System   VIDAA
2056  TOSHIBA  Ultra HD LED    50  Operating System   VIDAA
2058  TOSHIBA        HD LED    32  Operating System   VIDAA
2311  TOSHIBA  Ultra HD LED    65  Operating System   VIDAA
2353  TOSHIBA  Ultra HD LED    55  Operating System   VIDAA
2442  TOSHIBA  Ultra HD LED    43  Operating System   VIDAA
2700  TOSHIBA   Full HD LED    43  Operating System   VIDAA
2701  TOSHIBA  Ultra HD LED    65  Operating System   VIDAA
2702  TOSHIBA   Full HD LED    49  Operating System   VIDAA
2703  TOSHIBA  Ultra HD LED    65  Operating System   VIDAA
2736  TOSHIBA  Ultra HD LED    55            Rating     4.3
2755  TOSHIBA  Ultra HD LED    43            Rating     4.3
2762  TOSHIBA        HD LED    32            Rating     4.4
2868  TOSHIBA   Full HD LED    43            Rating     4.4
2968  TOSHIBA  Ultra HD LED    50            Rating     4.3
2970  TOSHIBA        HD LED    32            Rating     4.3
3223  TOSHIBA  Ultra HD LED    65            Rating     NaN
3265  TOSHIBA  Ultra HD LED    55            Rating     4.3
3354  TOSHIBA  Ultra HD LED    43            Rating     NaN
3612  TOSHIBA   Full HD LED    43            Rating     NaN
3613  TOSHIBA  Ultra HD LED    65            Rating     4.5
3614  TOSHIBA   Full HD LED    49            Rating     NaN
3615  TOSHIBA  Ultra HD LED    65            Rating     NaN